name: Robo Esoterico Automatico

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  postar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: |
          pip install google-api-python-client google-auth groq

      - name: Rodar o robo
        env:
          BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
          BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
          BLOGGER_ID_HOROSCOPO: ${{ secrets.BLOGGER_ID }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python horoscopo_diario.py
